{
  "openapi": "3.0.3",
  "info": {
    "title": "Access microservice",
    "description": "This microservice is used to manage all the informations and processes about the user, like registration, login and changing informations",
    "version": "1.3.3"
  },
  "externalDocs": {
    "description": "GitHub page",
    "url": "https://github.com/IntelligentBackpack/Microservice_Access"
  },
  "servers": [
    {
      "url": "https://accessmicroservice.azurewebsites.net"
    }
  ],
  "tags": [
    {
      "name": "register",
      "description": "Let you register an user"
    },
    {
      "name": "login",
      "description": "Let you login in the system"
    },
    {
      "name": "remove",
      "description": "Let you delete the created user"
    },
    {
      "name": "utility",
      "description": "Let you get/change informations about the user"
    }
  ],
  "paths": {
    "/register/": {
      "put": {
        "tags": [
          "register"
        ],
        "summary": "Register an user in the system",
        "description": "Register an user, with the given informations, in the system",
        "requestBody": {
          "description": "Data needed for register an user",
          "content": {
            "application/protobuf.User": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "messageReturn": {
                  "summary": "Input data",
                  "value": {
                    "email": "string",
                    "password": "string",
                    "nome": "string",
                    "cognome": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "email": "string",
                      "password": "string",
                      "nome": "string",
                      "cognome": "string",
                      "role": 0
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Message wrong formatted. Require Email, Password, Nome, Cognome fields. <br> Email already taken. <br> Password must contain minimum eight characters, at least one uppercase letter, one lowercase letter and one number!",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Wrong request",
                    "value": {
                      "message": "Message wrong formatted. Require Email, Password, Nome, Cognome fields."
                    }
                  },
                  "messageReturn2": {
                    "summary": "Email taken",
                    "value": {
                      "message": "Email already taken."
                    }
                  },
                  "messageReturn3": {
                    "summary": "Bad password",
                    "value": {
                      "message": "Password must contain minimum eight characters, at least one uppercase letter, one lowercase letter and one number!"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/login/": {
      "post": {
        "tags": [
          "login"
        ],
        "summary": "Validate user credentials",
        "description": "Validate user credentials passed for logging in the system",
        "requestBody": {
          "description": "Data needed for validate an user",
          "content": {
            "application/protobuf.User": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "messageReturn": {
                  "summary": "Input data",
                  "value": {
                    "email": "string",
                    "password": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Confirmed login.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Confirmed login.",
                      "user": {
                        "email": "string",
                        "password": "string",
                        "nome": "string",
                        "cognome": "string",
                        "istituto": {
                          "ID": "integer",
                          "IstitutoNome": "string",
                          "IstitutoCitta": "string"
                        },
                        "role": "integer",
                        "classe": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Wrong credentials.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Wrong credentials."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/remove/": {
      "delete": {
        "tags": [
          "remove"
        ],
        "summary": "Remove an user",
        "description": "Remove a given user from the system",
        "requestBody": {
          "description": "Data needed for remove an user",
          "content": {
            "application/protobuf.User": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "messageReturn": {
                  "summary": "Input data",
                  "value": {
                    "email": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "User deleted.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "User deleted."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/get_istituto/": {
      "get": {
        "tags": [
          "utility"
        ],
        "summary": "Get informations of an institute",
        "description": "Get informations of an institute",
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "ID of the institute",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Confirmed login.",
            "content": {
              "application/protobuf.Istituto": {
                "schema": {
                  "$ref": "#/components/schemas/Istituto"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Default istituto (no istitute found)",
                    "value": {
                      "ID": "integer",
                      "IstitutoNome": "string",
                      "IstitutoCitta": "string"
                    }
                  },
                  "messageReturn2": {
                    "summary": "Istituto found",
                    "value": {
                      "ID": "integer",
                      "IstitutoNome": "string",
                      "IstitutoCitta": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/get_istituti/": {
      "get": {
        "tags": [
          "utility"
        ],
        "summary": "Get informations of an institute",
        "description": "Get informations of an institute",
        "responses": {
          "200": {
            "description": "Confirmed login.",
            "content": {
              "application/protobuf.Response_Istituti": {
                "schema": {
                  "$ref": "#/components/schemas/Response_Istituti"
                },
                "examples": {
                  "Return data": {
                    "summary": "Return data",
                    "value": {
                      "istituti": "proto.istituti[]"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/emailExists/": {
      "get": {
        "tags": [
          "utility"
        ],
        "summary": "Verify if an user exists",
        "description": "Verify if an user exists, passing his email",
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "description": "Email of the user",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/protobuf.User": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "user": {
                        "email": "string",
                        "password": "string",
                        "nome": "string",
                        "cognome": "string",
                        "istituto": {
                          "ID": "integer",
                          "IstitutoNome": "string",
                          "IstitutoCitta": "string"
                        },
                        "role": "integer",
                        "classe": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Not found",
            "content": {
              "application/protobuf.User": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "user": {
                        "email": "string",
                        "password": "string",
                        "nome": "string",
                        "cognome": "string",
                        "istituto": {
                          "ID": "integer",
                          "IstitutoNome": "string",
                          "IstitutoCitta": "string"
                        },
                        "role": "integer",
                        "classe": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/verifyPrivileges_HIGH/": {
      "get": {
        "tags": [
          "utility"
        ],
        "summary": "Verify if an user have high privileges",
        "description": "Verify if an user exists, passed by email, have high privileges (Istituto, Owner)",
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "description": "Email of the user",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/protobuf.BasicMessage": {
                "schema": {
                  "$ref": "#/components/schemas/BasicMessage"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "High"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Not permissions",
            "content": {
              "application/protobuf.BasicMessage": {
                "schema": {
                  "$ref": "#/components/schemas/BasicMessage"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/verifyPrivileges_LOW/": {
      "get": {
        "tags": [
          "utility"
        ],
        "summary": "Verify if an user have Low privileges",
        "description": "Verify if an user exists, passed by email, have low privileges (Professor, Istituto, Owner)",
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "description": "Email of the user",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/protobuf.BasicMessage": {
                "schema": {
                  "$ref": "#/components/schemas/BasicMessage"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Low"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Not permissions",
            "content": {
              "application/protobuf.BasicMessage": {
                "schema": {
                  "$ref": "#/components/schemas/BasicMessage"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/change_nome/": {
      "post": {
        "tags": [
          "utility"
        ],
        "summary": "Change nome",
        "description": "Change the nome of a given user, passed by email",
        "requestBody": {
          "content": {
            "application/protobuf.User": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "messageReturn": {
                  "summary": "Input data",
                  "value": {
                    "email": "string",
                    "name": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Confirmed change to name.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Confirmed change to name.",
                      "user": {
                        "email": "string",
                        "password": "string",
                        "nome": "string",
                        "cognome": "string",
                        "istituto": {
                          "ID": "integer",
                          "IstitutoNome": "string",
                          "IstitutoCitta": "string"
                        },
                        "role": "integer",
                        "classe": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Cannot change name",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Cannot change name"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/change_cognome/": {
      "post": {
        "tags": [
          "utility"
        ],
        "summary": "Change cognome",
        "description": "Change the cognome of a given user, passed by email",
        "requestBody": {
          "content": {
            "application/protobuf.User": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "messageReturn": {
                  "summary": "Input data",
                  "value": {
                    "email": "string",
                    "cognome": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Confirmed change to cognome.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Confirmed change to cognome.",
                      "user": {
                        "email": "string",
                        "password": "string",
                        "nome": "string",
                        "cognome": "string",
                        "istituto": {
                          "ID": "integer",
                          "IstitutoNome": "string",
                          "IstitutoCitta": "string"
                        },
                        "role": "integer",
                        "classe": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Cannot change cognome",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Cannot change cognome"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/change_email/": {
      "post": {
        "tags": [
          "utility"
        ],
        "summary": "Change email",
        "description": "Change the email of a given user, passed by the old email",
        "requestBody": {
          "content": {
            "application/protobuf.UserRequest_ChangeEmail": {
              "schema": {
                "$ref": "#/components/schemas/UserRequest_ChangeEmail"
              },
              "examples": {
                "messageReturn": {
                  "summary": "Input data",
                  "value": {
                    "new_Email": "string",
                    "user": {
                      "email": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Confirmed change to email.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Confirmed change to email.",
                      "user": {
                        "email": "string",
                        "password": "string",
                        "nome": "string",
                        "cognome": "string",
                        "istituto": {
                          "ID": "integer",
                          "IstitutoNome": "string",
                          "IstitutoCitta": "string"
                        },
                        "role": "integer",
                        "classe": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "New email already exists!",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "New email already exists!"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Cannot change email",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Cannot change email"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/change_password/": {
      "post": {
        "tags": [
          "utility"
        ],
        "summary": "Change password",
        "description": "Change the password of a given user, passed by the old email",
        "requestBody": {
          "content": {
            "application/protobuf.User": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "messageReturn": {
                  "summary": "Input data",
                  "value": {
                    "user": {
                      "email": "string",
                      "password": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Confirmed change to password.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Confirmed change to password.",
                      "user": {
                        "email": "string",
                        "password": "string",
                        "nome": "string",
                        "cognome": "string",
                        "istituto": {
                          "ID": "integer",
                          "IstitutoNome": "string",
                          "IstitutoCitta": "string"
                        },
                        "role": "integer",
                        "classe": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad password",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Password must contain minimum eight characters, at least one uppercase letter, one lowercase letter and one number!"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Cannot change password",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Cannot change password"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/change_istituto/": {
      "post": {
        "tags": [
          "utility"
        ],
        "summary": "Change istituto",
        "description": "Change the istituto of a given user, passed by the email",
        "requestBody": {
          "content": {
            "application/protobuf.PermissionRequest_ChangeInstitute": {
              "schema": {
                "$ref": "#/components/schemas/PermissionRequest_ChangeInstitute"
              },
              "examples": {
                "messageReturn": {
                  "summary": "Input data",
                  "value": {
                    "email_esecutore": "string",
                    "email_utenteFinale": "string",
                    "nuovo_istituto": "object"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Istituto changed successfully.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Istituto changed successfully."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "You can't do this.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "You can't do this."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Cannot change istituto.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Cannot change istituto."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/change_ruolo/": {
      "post": {
        "tags": [
          "utility"
        ],
        "summary": "Change ruolo",
        "description": "Change the ruolo of a given user, passed by the email",
        "requestBody": {
          "content": {
            "application/protobuf.PermissionRequest_ChangeRuolo": {
              "schema": {
                "$ref": "#/components/schemas/PermissionRequest_ChangeRuolo"
              },
              "examples": {
                "messageReturn": {
                  "summary": "Input data",
                  "value": {
                    "email_esecutore": "string",
                    "email_utenteFinale": "string",
                    "nuovo_ruolo": "object"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ruolo changed successfully.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Ruolo changed successfully."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "You can't do this.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "You can't do this."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Cannot change ruolo.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Cannot change ruolo."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/utility/change_classe/": {
      "post": {
        "tags": [
          "utility"
        ],
        "summary": "Change classe",
        "description": "Change the classe of a given user, passed by the email",
        "requestBody": {
          "content": {
            "application/protobuf.PermissionRequest_ChangeClasse": {
              "schema": {
                "$ref": "#/components/schemas/PermissionRequest_ChangeClasse"
              },
              "examples": {
                "messageReturn": {
                  "summary": "Input data",
                  "value": {
                    "email_esecutore": "string",
                    "email_utenteFinale": "string",
                    "nuova_classe": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Classe changed successfully.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Classe changed successfully."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "You can't do this.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "You can't do this."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Cannot change classe.",
            "content": {
              "application/protobuf.UserResponse": {
                "schema": {
                  "$ref": "#/components/schemas/UserResponse"
                },
                "examples": {
                  "messageReturn": {
                    "summary": "Return data",
                    "value": {
                      "message": "Cannot change classe."
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "BasicMessage": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        }
      },
      "UserResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "user": {
            "type": "object"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "nome": {
            "type": "string"
          },
          "cognome": {
            "type": "string"
          },
          "istituto": {
            "type": "object"
          },
          "role": {
            "type": "object"
          },
          "classe": {
            "type": "string"
          }
        }
      },
      "Istituto": {
        "type": "object",
        "properties": {
          "ID": {
            "type": "integer"
          },
          "IstitutoNome": {
            "type": "string"
          },
          "IstitutoCitta": {
            "type": "string"
          }
        }
      },
      "Response_Istituti": {
        "type": "object",
        "properties": {
          "istituti": {
            "type": "object"
          }
        }
      },
      "UserRequest_ChangeEmail": {
        "type": "object",
        "properties": {
          "nuova_Email": {
            "type": "string"
          },
          "user": {
            "type": "object"
          }
        }
      },
      "PermissionRequest_ChangeInstitute": {
        "type": "object",
        "properties": {
          "email_esecutore": {
            "type": "string"
          },
          "email_utenteFinale": {
            "type": "string"
          },
          "nuovo_istituto": {
            "type": "object"
          }
        }
      },
      "PermissionRequest_ChangeRuolo": {
        "type": "object",
        "properties": {
          "email_esecutore": {
            "type": "string"
          },
          "email_utenteFinale": {
            "type": "string"
          },
          "nuovo_ruolo": {
            "type": "object"
          }
        }
      },
      "PermissionRequest_ChangeClasse": {
        "type": "object",
        "properties": {
          "email_esecutore": {
            "type": "string"
          },
          "email_utenteFinale": {
            "type": "string"
          },
          "nuova_classe": {
            "type": "string"
          }
        }
      }
    }
  }
}